export { default as Home } from './home'
export { default as About } from './about'
export { default as HMRDemo } from './hmrDemo'
export { default as HookDemo } from './hookDemo'
export { default as NotFound } from './404'